# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# Shield for default ZMK display: nice_view
---
include:
#Dongle
  - board: seeeduino_xiao_ble
    shield: corne_xiao_v2_dongle rgbled_adapter dongle_display_view_seeeduino_xiao_ble
    cmake-args: -DCONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=n -DCONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=n
    snippet: studio-rpc-usb-uart
    
#Left
  - board: seeeduino_xiao_ble
    shield: corne_xiao_v2_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

#Right
  - board: seeeduino_xiao_ble
    shield: corne_xiao_v2_right rgbled_adapter

#Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset